#HMDB METABOLITES PROCESSING 9
#08/24/13
#Get rid of synonym UNIPROTS

import pickle

#LOAD UNIPROT JOB TO DICT
FILE_IN1=open("DATABASES/HMDB_SOURCE/UNIPROT_JOB/UNIPROT_MAPPING1_082513.tab")
UNI_OBJ=[X.split("\t") for X in FILE_IN1.read().splitlines()]
FILE_IN1.close()

UNI_MAPPER=dict((X[0], X[1]) for X in UNI_OBJ)
UNI_MAPPER["A8MYA6"]="A8MYA6" #TEMPORAL FIX

#LOAD HMDB FILE
PICKLE_IN1=open("DATABASES/OBJECTS/DICT_METABOLITE_TO_UNIPROTS_HMDB_FILTERED.pi")
MET_TO_UNI_LIST=pickle.load(PICKLE_IN1)
PICKLE_IN1.close()

#Get rid of water
for key_set in MET_TO_UNI_LIST.keys():
    if "Water" in key_set:
        del MET_TO_UNI_LIST[key_set]

#RESOLVE SYNONYMS
COUNT=0
COUNT1=0
for met in MET_TO_UNI_LIST.keys():
    PRE=len(MET_TO_UNI_LIST[met])
    MET_TO_UNI_LIST[met]=set([UNI_MAPPER[UNI] for UNI in MET_TO_UNI_LIST[met]])
    POST=len(MET_TO_UNI_LIST[met])
    if PRE>POST:
        COUNT=COUNT+1
        COUNT1=COUNT1+(PRE-POST)
print COUNT, COUNT1

#SAVE FIXED VERSION TO UPDATED OBJET {MET_SET=UNIPROT_SET}
PICKLE_OUT1=open("DATABASES/OBJECTS/DICT_METABOLITE_TO_UNIPROTS_HMDB_FILTERED2.pi","w")
pickle.dump(MET_TO_UNI_LIST, PICKLE_OUT1)
PICKLE_OUT1.close()
