#HMDB METABOLITES PROCESSING 10
#08/25/13
#CHANGE UNIPROTS TO GENES IF THEY HAVE IT WITH UNIPROT JOB 2

import pickle

#PROCESS UNIPROT JOB 2 INTO UNIPROT TO GENE DICT (NO SYNOYMS!!!) OF THOSE THAT HAVE A GENE NAME 
FILE_IN1=open("DATABASES/HMDB_SOURCE/UNIPROT_JOB/UNIPROT_MAPPING2_082513.tab")
UNI_JOB2=[X.split("\t") for X in FILE_IN1.read().splitlines()]
FILE_IN1.close()

UNI_TO_GENE=dict((X[0], X[4].split()[0].upper().strip()) for X in UNI_JOB2 if len(X[4])!=0)
UNI_TO_GENE["A8MYA6"]="SHMT1" #FIXED

#LOAD HMDB OBJECT
PICKLE_IN1=open("DATABASES/OBJECTS/DICT_METABOLITE_TO_UNIPROTS_HMDB_FILTERED2.pi")
MET_TO_UNI_SET=pickle.load(PICKLE_IN1)
PICKLE_IN1.close()

#IMPLEMENT GENES TO HMDB IF PRESENT AND FIX SYNOYMS IF ANY
for MET in MET_TO_UNI_SET.keys():
    TRANSLATED=set([UNI_TO_GENE[met] for met in MET_TO_UNI_SET[MET] if met in UNI_TO_GENE])
    UNTRANSLATED=set([met for met in MET_TO_UNI_SET[MET] if met not in UNI_TO_GENE])
    MET_TO_UNI_SET[MET]=TRANSLATED | UNTRANSLATED

#SAVE FIXED VERSION TO UPDATED OBJET {MET_SET=UNIPROT_SET}
PICKLE_OUT1=open("DATABASES/OBJECTS/DICT_METABOLITE_TO_UNIPROTS_HMDB_FILTERED3.pi","w")
pickle.dump(MET_TO_UNI_SET, PICKLE_OUT1)
PICKLE_OUT1.close()