#HMDB METABOLITES PROCESSING 10
#08/25/13
#DO JACCARD NETWORK WEIGHTED FILE ON FIXED NETWORK

from FUNCTIONS import JACCARD
import pickle

#LOAD HMDB OBJECT
PICKLE_IN1=open("DATABASES/OBJECTS/DICT_METABOLITE_TO_UNIPROTS_HMDB_FILTERED3.pi")
MET_TO_UNIGENE_SET=pickle.load(PICKLE_IN1)
PICKLE_IN1.close()

#SWITH TO UNIGENE KEY DICT
UNIGENE_LIST=set([UNIGENE for SET in MET_TO_UNIGENE_SET.values() for UNIGENE in SET])
UNIGENE_TO_MET_SET=dict((X, []) for X in UNIGENE_LIST)

for record in MET_TO_UNIGENE_SET.keys():
    
    
            