#IMPROVE UNIPROT_TO_GENES_OBJECTS BY REMOVING UNIPROT WITH EMPTY GENE VALUES
#08/06/13 HAVE THE FORMAT {UNIPROT:[GENE1, GENE2,...]} 
#DICTS HAVE THE FORMAT
import pickle

#ALL
PICKLE_IN1=open("DATABASES/OBJECTS/DICT_UNIPROT_TO_GENES.pi")
ALL=pickle.load(PICKLE_IN1)
print len(ALL)
PICKLE_IN1.close()

ALL_FIXED=dict((X, ALL[X]) for X in ALL.iterkeys() if len(ALL[X])>0)
print len(ALL_FIXED)

PICKLE_OUT1=open("DATABASES/OBJECTS/DICT_UNIPROT_TO_GENES.pi", "w")
pickle.dump(ALL_FIXED, PICKLE_OUT1)

#REVIEWED
PICKLE_IN2=open("DATABASES/OBJECTS/DICT_UNIPROT_TO_GENES_REVIEWED.pi")
REVIEWED=pickle.load(PICKLE_IN2)
print len(REVIEWED)
PICKLE_IN2.close()

REVIEWED_FIXED=dict((X, REVIEWED[X]) for X in REVIEWED.iterkeys() if len(REVIEWED[X])>0)
print len(REVIEWED_FIXED)

PICKLE_OUT2=open("DATABASES/OBJECTS/DICT_UNIPROT_TO_GENES_REVIEWED.pi", "w")
pickle.dump(REVIEWED_FIXED, PICKLE_OUT2)

print REVIEWED_FIXED